trigger:
  tags:
    include:
      - v.*
  branches:
    include:
      - develop
      - master
  paths:
    exclude:
      - README.md

pr:
  - master

pool: server

steps:
  - task: InvokeRESTAPI@1
    inputs:
      connectionType: 'connectedServiceName'
      serviceConnection: 'Pipelines'
      method: 'POST'
      urlSuffix: '/edgeworx/_apis/build/builds?api-version=5.0'
      body: "{\"Parameters\":\"{\\\"images.controller\\\": \\\"$(test)\\\", \\\"images.connector\\\": \\\"$(test)\\\"}\", \"Definition\":{\"id\":\"5\"}}"
      waitForCompletion: 'false'

#  - task: InvokeRESTAPI@1
#    inputs:
#      connectionType: 'connectedServiceName'
#      serviceConnection: 'Pipelines'
#      method: 'GET'
#      urlSuffix: /edgeworx/_apis/build/definitions?api-version=5.0
#      waitForCompletion: 'true'

  # - task: InvokeRESTAPI@1
  #   inputs:
  #     connectionType: 'connectedServiceName'
  #     serviceConnection: 'Pipelines'
  #     method: 'POST'
  #     urlSuffix: /edgeworx/_apis/build/builds?api-version=5.0&organization=edgeworx&project=edgeworx&sourceBuildId=5
  #     body: |
  #       { 
  #         "parameters": "{ 
  #           \"images.controller\":  \"test\"
  #           }",
  #         "buildNumber": 5
  #       }

#  - task: InvokeRESTAPI@1
#    inputs:
#      connectionType: 'connectedServiceName'
#      serviceConnection: 'Pipelines'
#      method: 'POST'
#      urlSuffix: /edgeworx/_apis/build/builds?api-version=5.0&organization=edgeworx&project=edgeworx
#      body: |
#        { "parameters": "{ 
#            \"images.controller\":  \"test\"
#            }",
#          "definition": "{
#            \"_links\": {
#             \"self\": {
#               \"href\": \"https://dev.azure.com/edgeworx/02af0506-ca6c-431d-8a76-cd5bfa0783c0/_apis/build/Definitions/5?revision=7\"
#             },
#             \"web\": {
#               \"href\": \"https://dev.azure.com/edgeworx/02af0506-ca6c-431d-8a76-cd5bfa0783c0/_build/definition?definitionId=5\"
#             },
#             \"editor\": {
#               \"href\": \"https://dev.azure.com/edgeworx/02af0506-ca6c-431d-8a76-cd5bfa0783c0/_build/designer?id=5&_a=edit-build-definition\"
#             },
#             \"badge\": {
#               \"href\": \"https://dev.azure.com/edgeworx/02af0506-ca6c-431d-8a76-cd5bfa0783c0/_apis/build/status/5\"
#             }
#           },
#           \"quality\": \"definition\",
#           \"authoredBy\": {
#             \"displayName\": \"serge\",
#             \"url\": \"https://spsprodcus2.vssps.visualstudio.com/Aa165685e-f191-49b1-92d0-2ce1d338b7c0/_apis/Identities/809eb490-8d69-65ba-a462-0764cd512243\",
#             \"_links\": {
#               \"avatar\": {
#                 \"href\": \"https://dev.azure.com/edgeworx/_apis/GraphProfile/MemberAvatars/msa.ODA5ZWI0OTAtOGQ2OS03NWJhLWE0NjItMDc2NGNkNTEyMjQz\"
#               }
#             },
#             \"id\": \"809eb490-8d69-65ba-a462-0764cd512243\",
#             \"uniqueName\": \"serge@edgeworx.io\",
#             \"imageUrl\": \"https://dev.azure.com/edgeworx/_apis/GraphProfile/MemberAvatars/msa.ODA5ZWI0OTAtOGQ2OS03NWJhLWE0NjItMDc2NGNkNTEyMjQz\",
#             \"descriptor\": \"msa.ODA5ZWI0OTAtOGQ2OS03NWJhLWE0NjItMDc2NGNkNTEyMjQz\"
#           },
#           \"drafts\": [],
#           \"queue\": {
#             \"_links\": {
#               \"self\": {
#                 \"href\": \"https://dev.azure.com/edgeworx/_apis/build/Queues/16\"
#               }
#             },
#             \"id\": 16,
#             \"name\": \"Hosted Ubuntu 1604\",
#             \"url\": \"https://dev.azure.com/edgeworx/_apis/build/Queues/16\",
#             \"pool\": {
#               \"id\": 8,
#               \"name\": \"Hosted Ubuntu 1604\",
#               \"isHosted\": true
#             }
#           },
#           \"id\": 5,
#           \"name\": \"eclipse-iofog.platform\",
#           \"url\": \"https://dev.azure.com/edgeworx/02af0506-ca6c-431d-8a76-cd5bfa0783c0/_apis/build/Definitions/5?revision=7\",
#           \"uri\": \"vstfs:///Build/Definition/5\",
#           \"path\": \"\\\",
#           \"type\": \"build\",
#           \"queueStatus\": \"enabled\",
#           \"revision\": 7,
#           \"createdDate\": \"2019-05-04T07:12:57.677Z\",
#           \"project\": {
#             \"id\": \"02af0506-ca6c-431d-8a76-cd5bfa0783c0\",
#             \"name\": \"edgeworx\",
#             \"url\": \"https://dev.azure.com/edgeworx/_apis/projects/02af0506-ca6c-431d-8a76-cd5bfa0783c0\",
#             \"state\": \"wellFormed\",
#             \"revision\": 22,
#             \"visibility\": \"private\",
#             \"lastUpdateTime\": \"2019-05-02T01:12:59.29Z\"
#           }
#          }"
#        }
#      waitForCompletion: 'false'